name: Update Chrome OS User-Agent

on:
    schedule:
        - cron: "0 1 * * *" # Every day at 01:00 UTC
    workflow_dispatch:

jobs:
    update_ua:
        name: Check and commit last Chrome version
        runs-on: ubuntu-latest
        outputs:
            chrome_version: ${{ steps.ua_update.outputs.chrome_version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - uses: jdx/mise-action@v4
              with:
                  install: true
                  cache: true
                  experimental: true
            - name: Execute User Agent update script
              id: ua_update
              run: mise run ua-update
            - name: Update metadata.json with new Chrome version
              if: ${{ steps.ua_update.outputs.chrome_version }}
              run: |
                  METADATA_FILE=$(cat metadata.json | jq '.version.release_notes."en-US"="Updated User Agent string to ${{ steps.ua_update.outputs.chrome_version }}"')
                  echo "$METADATA_FILE" > metadata.json
            - name: Commit
              id: commit
              if: ${{ steps.ua_update.outputs.chrome_version }}
              run: |
                  git config --global user.name 'Axel Leroy'
                  git config --global user.email 'axeleroy@users.noreply.github.com'
                  git add metadata.json
                  pnpm prepare
                  git commit -am "Updated User Agent string to ${{ steps.ua_update.outputs.chrome_version }}"
                  git push
    publish:
        uses: axeleroy/slack-app-in-tab/.github/workflows/publish.yml@main
        needs:
            - update_ua
        if: ${{ needs.update_ua.outputs.chrome_version }}
